import { toPropertyAccessor, toTypeName } from '../naming.js';
import type { ParsedDocument, ParsedOperation } from '../types.js';

function renderTemplatePath(path: string, operation: ParsedOperation): string {
  let rendered = path;

  for (const parameter of operation.pathParameters) {
    rendered = rendered.replace(
      `{${parameter.name}}`,
      `\${encodeURIComponent(String(request.${toPropertyAccessor(parameter.name)}))}`,
    );
  }

  return `\`${rendered}\``;
}

function renderQueryLines(operation: ParsedOperation): string[] {
  if (operation.queryParameters.length === 0) {
    return [];
  }

  return operation.queryParameters.map((parameter) => {
    const accessor = `request.${toPropertyAccessor(parameter.name)}`;
    return [
      `      if (${accessor} !== undefined) {`,
      `        searchParams.set(${JSON.stringify(parameter.name)}, String(${accessor}));`,
      '      }',
    ].join('\n');
  });
}

function renderMethodSignature(operation: ParsedOperation): string {
  if (!operation.hasRequestShape) {
    return `${operation.functionName}(init?: RequestInit): Promise<${operation.responseTypeName}>;`;
  }

  if (operation.hasRequiredRequestFields) {
    return `${operation.functionName}(request: ${operation.requestTypeName}, init?: RequestInit): Promise<${operation.responseTypeName}>;`;
  }

  return `${operation.functionName}(request?: ${operation.requestTypeName}, init?: RequestInit): Promise<${operation.responseTypeName}>;`;
}

function renderMethodImplementation(operation: ParsedOperation): string {
  const requestParameter = operation.hasRequestShape
    ? operation.hasRequiredRequestFields
      ? 'request'
      : 'request = {}'
    : '';
  const queryLines = renderQueryLines(operation);
  const bodyContent =
    operation.requestBody?.contentType === 'application/json' ||
    operation.requestBody?.contentType?.endsWith('+json')
      ? [
          '      const body = request.body !== undefined ? JSON.stringify(request.body) : undefined;',
          "      headers.set('content-type', 'application/json');",
        ].join('\n')
      : '      const body = undefined;';

  return [
    `    async ${operation.functionName}(${requestParameter}${requestParameter ? ', ' : ''}init?: RequestInit): Promise<${operation.responseTypeName}> {`,
    `      const url = new URL(${renderTemplatePath(operation.path, operation)}, resolveBaseUrl(config.baseUrl));`,
    '      const searchParams = url.searchParams;',
    ...(queryLines.length > 0 ? queryLines : ['      void searchParams;']),
    '      const headers = new Headers(config.headers);',
    bodyContent,
    '      const response = await runtimeFetch(url, {',
    '        ...init,',
    `        method: ${JSON.stringify(operation.method.toUpperCase())},`,
    '        body,',
    '        headers: mergeHeaders(headers, init?.headers),',
    '      });',
    '',
    '      if (!response.ok) {',
    '        throw await ApiError.fromResponse(response);',
    '      }',
    '',
    `      return parseResponse<${operation.responseTypeName}>(response);`,
    '    },',
  ].join('\n');
}

export function generateClientSource(parsed: ParsedDocument): string {
  const clientName = `${toTypeName(parsed.sdkName)}Client`;
  const interfaceLines = parsed.operations.map(
    (operation) => `  ${renderMethodSignature(operation)}`,
  );
  const methodLines = parsed.operations.map((operation) => renderMethodImplementation(operation));

  return [
    '/* eslint-disable */',
    '/**',
    ' * Auto-generated by api-sdk-generator.',
    ' * Do not edit manually.',
    ' */',
    '',
    'import type {',
    ...parsed.operations.flatMap((operation) => [
      `  ${operation.requestTypeName},`,
      `  ${operation.responseTypeName},`,
    ]),
    "} from './types';",
    '',
    'export interface ClientConfig {',
    '  baseUrl?: string;',
    '  fetch?: typeof fetch;',
    '  headers?: HeadersInit;',
    '}',
    '',
    `export interface ${clientName} {`,
    ...interfaceLines,
    '}',
    '',
    'export class ApiError extends Error {',
    '  public readonly body: unknown;',
    '  public readonly status: number;',
    '',
    '  public constructor(status: number, message: string, body: unknown) {',
    '    super(message);',
    '    this.name = "ApiError";',
    '    this.status = status;',
    '    this.body = body;',
    '  }',
    '',
    '  public static async fromResponse(response: Response): Promise<ApiError> {',
    '    const contentType = response.headers.get("content-type") ?? "";',
    '    const body = contentType.includes("application/json") ? await response.json() : await response.text();',
    '    return new ApiError(response.status, `Request failed with status ${response.status}`, body);',
    '  }',
    '}',
    '',
    'export function createClient(config: ClientConfig = {}): ' + clientName + ' {',
    '  const runtimeFetch = config.fetch ?? globalThis.fetch;',
    '',
    '  if (!runtimeFetch) {',
    '    throw new Error("Fetch API is not available in the current runtime.");',
    '  }',
    '',
    '  return {',
    ...methodLines,
    '  };',
    '}',
    '',
    'function resolveBaseUrl(baseUrl?: string): string {',
    `  return baseUrl ?? ${JSON.stringify(parsed.defaultBaseUrl ?? 'http://localhost')};`,
    '}',
    '',
    'async function parseResponse<T>(response: Response): Promise<T> {',
    '  if (response.status === 204) {',
    '    return undefined as T;',
    '  }',
    '',
    '  const contentType = response.headers.get("content-type") ?? "";',
    '',
    '  if (contentType.includes("application/json")) {',
    '    return (await response.json()) as T;',
    '  }',
    '',
    '  return (await response.text()) as T;',
    '}',
    '',
    'function mergeHeaders(baseHeaders: Headers, initHeaders?: HeadersInit): Headers {',
    '  const merged = new Headers(baseHeaders);',
    '',
    '  if (initHeaders) {',
    '    const overlay = new Headers(initHeaders);',
    '    overlay.forEach((value, key) => merged.set(key, value));',
    '  }',
    '',
    '  return merged;',
    '}',
    '',
  ].join('\n');
}
