import { toTypeName } from '../naming.js';
import type { ParsedDocument, ParsedOperation } from '../types.js';

function renderTemplatePath(path: string, operation: ParsedOperation): string {
  const parts: string[] = [];
  let offset = 0;
  for (const match of path.matchAll(/\{([^}]+)\}/g)) {
    const parameter = operation.pathParameters.find((item) => item.name === match[1]);
    if (!parameter) continue;
    parts.push(JSON.stringify(path.slice(offset, match.index)));
    parts.push(`encodeURIComponent(String(request[${JSON.stringify(parameter.name)}]))`);
    offset = match.index + match[0].length;
  }
  parts.push(JSON.stringify(path.slice(offset)));
  return parts.join(' + ');
}

function renderQueryLines(operation: ParsedOperation): string[] {
  return operation.queryParameters.map((parameter) => {
    const style = parameter.style ?? 'form';
    const explode = parameter.explode ?? style === 'form';
    const separator = style === 'spaceDelimited' ? ' ' : style === 'pipeDelimited' ? '|' : ',';
    return `      appendQueryParameter(searchParams, ${JSON.stringify(parameter.name)}, request[${JSON.stringify(parameter.name)}], ${explode}, ${JSON.stringify(separator)});`;
  });
}

function renderMethodSignature(operation: ParsedOperation): string {
  if (!operation.hasRequestShape) {
    return `${operation.functionName}(init?: RequestInit): Promise<${operation.responseTypeName}>;`;
  }

  if (operation.hasRequiredRequestFields) {
    return `${operation.functionName}(request: ${operation.requestTypeName}, init?: RequestInit): Promise<${operation.responseTypeName}>;`;
  }

  return `${operation.functionName}(request?: ${operation.requestTypeName}, init?: RequestInit): Promise<${operation.responseTypeName}>;`;
}

function renderMethodImplementation(operation: ParsedOperation): string {
  const requestParameter = operation.hasRequestShape
    ? operation.hasRequiredRequestFields
      ? 'request'
      : 'request = {}'
    : '';
  const queryLines = renderQueryLines(operation);
  const bodyContent =
    operation.requestBody?.contentType === 'application/json' ||
    operation.requestBody?.contentType?.endsWith('+json')
      ? [
          '      const body = request.body !== undefined ? JSON.stringify(request.body) : undefined;',
          '      if (body !== undefined && !headers.has("content-type")) {',
          `        headers.set("content-type", ${JSON.stringify(operation.requestBody.contentType)});`,
          '      }',
        ].join('\n')
      : '      const body = undefined;';

  return [
    `    async ${operation.functionName}(${requestParameter}${requestParameter ? ', ' : ''}init?: RequestInit): Promise<${operation.responseTypeName}> {`,
    `      const url = resolveRequestUrl(resolveBaseUrl(config.baseUrl), ${renderTemplatePath(operation.path, operation)});`,
    '      const searchParams = url.searchParams;',
    ...(queryLines.length > 0 ? queryLines : ['      void searchParams;']),
    '      const headers = new Headers(config.headers);',
    bodyContent,
    '      const response = await runtimeFetch(url, {',
    '        ...init,',
    `        method: ${JSON.stringify(operation.method.toUpperCase())},`,
    '        body,',
    '        headers: mergeHeaders(headers, init?.headers),',
    '      });',
    '',
    '      if (!response.ok) {',
    '        throw await ApiError.fromResponse(response);',
    '      }',
    '',
    `      return parseResponse<${operation.responseTypeName}>(response);`,
    '    },',
  ].join('\n');
}

export function generateClientSource(parsed: ParsedDocument): string {
  const clientName = `${toTypeName(parsed.sdkName)}Client`;
  const interfaceLines = parsed.operations.map(
    (operation) => `  ${renderMethodSignature(operation)}`,
  );
  const methodLines = parsed.operations.map((operation) => renderMethodImplementation(operation));

  return [
    '/* eslint-disable */',
    '/**',
    ' * Auto-generated by api-sdk-generator.',
    ' * Do not edit manually.',
    ' */',
    '',
    ...(parsed.operations.length > 0
      ? [
          'import type {',
          ...parsed.operations.flatMap((operation) => [
            ...(operation.hasRequestShape ? [`  ${operation.requestTypeName},`] : []),
            `  ${operation.responseTypeName},`,
          ]),
          "} from './types.js';",
          '',
        ]
      : []),
    'export interface ClientConfig {',
    '  baseUrl?: string;',
    '  fetch?: typeof fetch;',
    '  headers?: HeadersInit;',
    '}',
    '',
    `export interface ${clientName} {`,
    ...interfaceLines,
    '}',
    '',
    'export class ApiError extends Error {',
    '  public readonly body: unknown;',
    '  public readonly status: number;',
    '  public readonly headers: Headers;',
    '',
    '  public constructor(status: number, message: string, body: unknown, headers: Headers = new Headers()) {',
    '    super(message);',
    '    this.name = "ApiError";',
    '    this.status = status;',
    '    this.body = body;',
    '    this.headers = headers;',
    '  }',
    '',
    '  public static async fromResponse(response: Response): Promise<ApiError> {',
    '    const body = await parseResponseBody(response.clone()).catch(() => response.text());',
    '    return new ApiError(response.status, `Request failed with status ${response.status}`, body, response.headers);',
    '  }',
    '}',
    '',
    'export function createClient(config: ClientConfig = {}): ' + clientName + ' {',
    '  const runtimeFetch = config.fetch ?? globalThis.fetch;',
    '',
    '  if (!runtimeFetch) {',
    '    throw new Error("Fetch API is not available in the current runtime.");',
    '  }',
    '',
    '  return {',
    ...methodLines,
    '  };',
    '}',
    '',
    ...(parsed.operations.length > 0
      ? [
          'function resolveBaseUrl(baseUrl?: string): string {',
          `  return baseUrl ?? ${JSON.stringify(parsed.defaultBaseUrl ?? 'http://localhost')};`,
          '}',
          '',
          'function resolveRequestUrl(baseUrl: string, requestPath: string): URL {',
          '  const normalizedBaseUrl = baseUrl.endsWith("/") ? baseUrl : `${baseUrl}/`;',
          '  return new URL(requestPath.replace(/^\\/+/, ""), normalizedBaseUrl);',
          '}',
          '',
          'async function parseResponse<T>(response: Response): Promise<T> {',
          '  return (await parseResponseBody(response)) as T;',
          '}',
          '',
        ]
      : []),
    'async function parseResponseBody(response: Response): Promise<unknown> {',
    '  if (response.status === 204 || response.status === 205) {',
    '    return undefined;',
    '  }',
    '',
    '  const body = await response.text();',
    '',
    '  if (!body) {',
    '    return undefined;',
    '  }',
    '',
    '  const contentType = response.headers.get("content-type") ?? "";',
    '  return isJsonContentType(contentType) ? (JSON.parse(body) as unknown) : body;',
    '}',
    '',
    'function isJsonContentType(contentType: string): boolean {',
    '  const mediaType = contentType.split(";", 1)[0].trim().toLowerCase();',
    '  return mediaType === "application/json" || mediaType.endsWith("+json");',
    '}',
    '',
    ...(parsed.operations.some((operation) => operation.queryParameters.length > 0)
      ? [
          'function appendQueryParameter(params: URLSearchParams, name: string, value: unknown, explode: boolean, separator: string): void {',
          '  if (value === undefined) return;',
          '  if (Array.isArray(value)) {',
          '    if (explode) {',
          '      for (const item of value) params.append(name, String(item));',
          '    } else {',
          '      params.set(name, value.map(String).join(separator));',
          '    }',
          '  } else {',
          '    params.set(name, String(value));',
          '  }',
          '}',
          '',
        ]
      : []),
    ...(parsed.operations.length > 0
      ? [
          'function mergeHeaders(baseHeaders: Headers, initHeaders?: HeadersInit): Headers {',
          '  const merged = new Headers(baseHeaders);',
          '',
          '  if (initHeaders) {',
          '    const overlay = new Headers(initHeaders);',
          '    overlay.forEach((value, key) => merged.set(key, value));',
          '  }',
          '',
          '  return merged;',
          '}',
          '',
        ]
      : []),
  ].join('\n');
}
