import type { ParsedDocument } from '../types.js';

export function generateGeneratedReadme(parsed: ParsedDocument): string {
  const exampleOperation = parsed.operations[0];
  const exampleCall = exampleOperation?.hasRequestShape
    ? `${exampleOperation.functionName}({ /* request */ })`
    : `${exampleOperation?.functionName ?? 'listResources'}()`;

  return [
    `# ${parsed.sdkName}`,
    '',
    'This SDK was generated by `api-sdk-generator`.',
    '',
    '## Usage',
    '',
    '```ts',
    "import { createClient } from './index';",
    '',
    'const client = createClient({',
    `  baseUrl: ${JSON.stringify(parsed.defaultBaseUrl ?? 'https://api.example.com')},`,
    '});',
    '',
    `await client.${exampleCall};`,
    '```',
    '',
  ].join('\n');
}
